apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloploy-web
  namespace: cloploy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: app.cloploy.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloploy-web
                port:
                  number: 80
