apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloploy-ingress
  namespace: cloploy
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/security-groups: sg-0c80348e99d0d7641
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "false"
spec:
  ingressClassName: alb
  rules:
    - host: app.cloploy.app
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cloploy-api
                port:
                  number: 3121
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloploy-web
                port:
                  number: 80
