apiVersion: v1
kind: Secret
metadata:
  name: cloploy-secrets
  namespace: cloploy
type: Opaque
stringData:
  JWT_SECRET: super-secret-jwt-key-2026
  MONGODB_URI: mongodb://cloploy-mongodb:27017/cloploy
