jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousJobStatusPermission: false

unclassified:
  sonarGlobalConfiguration:
    installations:
      - name: "SonarQubeServer"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonarqube-token"