apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloploy-saas-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/tharaneesh/cloploy-platform.git'
    targetRevision: HEAD
    path: infra/helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloploy-users
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
